name: Checkout and Setup
description: 'Installs NPM Dependencies'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "npm"

    - name: Install Node Modules from NPM
      shell: bash
      run: npm ci
